development:
  host: localhost
  port: 5432
  database: risk_db
  username: postgres
  password: rootroot

production:
  host: prod-db-server
  port: 5432
  database: risk_db_prod
  username: prod_user
  password: rootroot